name: EJC
on:
  push:
    branches: [ejc]

jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - name: Pr Silvia
        uses: zzzze/webhook-trigger@v1.0.0
        with:
          webhook_url: "https://plesk6400.is.cc:8443/modules/git/public/web-hook.php?uuid=328c45f2-e65f-aea8-a8fd-baeacf358737"
          json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
