name: Consultório
on:
  push:
    branches: [main]

jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - name: Pr Silvia
        uses: zzzze/webhook-trigger@v1.0.0
        with:
          webhook_url: "https://plesk6400.is.cc:8443/modules/git/public/web-hook.php?uuid=cb6821ad-5225-24db-d511-90832a9a282f"
          json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
